project_id = "qcuhjcyjlkfizesndmth"

[functions.ai-sync-engine]
verify_jwt = false

[functions.ai-recommendation-engine]
verify_jwt = false

[functions.ai-predictive-analytics]
verify_jwt = false

[functions.ai-document-intelligence]
verify_jwt = false

[functions.ai-nlp-processor]
verify_jwt = false

[functions.system-engineer-discovery]
verify_jwt = false

[functions.ai-translation-engine]
verify_jwt = false

[functions.hf-document-processor]
verify_jwt = false

[functions.ai-agent-orchestrator]
verify_jwt = false

[functions.enhanced-aqlhr-ai]
verify_jwt = false

[functions.manus-image-generator]
verify_jwt = false

[functions.manus-ai-integration]
verify_jwt = false

[functions.gpt-oss-integration]
verify_jwt = false

[functions.gemini-analytics]
verify_jwt = false

[functions.send-auth-link]
verify_jwt = false

[functions.agent-cci-change-plan-v1]
verify_jwt = false

[functions.cci-seed-instrument-v1]
verify_jwt = false

[functions.cci-evidence-ingest-v1]
verify_jwt = false

[functions.cci-exports]
verify_jwt = false

[functions.cci-seed-demo-wave-v1]
verify_jwt = false

[functions.agent-skill-executor]
verify_jwt = false

[functions.sync-mol-v1]
verify_jwt = true

[functions.sync-qiwa-v1]
verify_jwt = true

[functions.sync-gosi-v1]
verify_jwt = true

[functions.sync-absher-v1]
verify_jwt = true

[functions.ask-aql-tools]
verify_jwt = true

[functions.secure-admin-wrapper]
verify_jwt = true

[functions.cron-dashboard-snapshot-daily-v1]
verify_jwt = false

[functions.compliance-autopilot-daily-v1]
verify_jwt = false

[functions.compliance-letter-generator]
verify_jwt = false

[functions.kernel-worker-v1]
verify_jwt = false