project_id = "qcuhjcyjlkfizesndmth"

[functions.ai-sync-engine]
verify_jwt = false

[functions.ai-recommendation-engine]
verify_jwt = false

[functions.ai-predictive-analytics]
verify_jwt = false

[functions.ai-document-intelligence]
verify_jwt = false

[functions.ai-nlp-processor]
verify_jwt = false

[functions.system-engineer-discovery]
verify_jwt = false

[functions.ai-translation-engine]
verify_jwt = false

[functions.hf-document-processor]
verify_jwt = false

[functions.ai-agent-orchestrator]
verify_jwt = false

[functions.enhanced-aqlhr-ai]
verify_jwt = false

[functions.manus-image-generator]
verify_jwt = false