/**
 * AQLHR Platform - Expert-Level RTL Language Context
 * Professional Arabic/English Language Management with RTL Support
 * @author AQLHR Development Team
 * @version 3.0.0
 */

import React, { createContext, useContext, useEffect, useState, ReactNode } from 'react';

// Types
export type Language = 'ar' | 'en';
export type Direction = 'rtl' | 'ltr';

export interface LanguageContextType {
  language: Language;
  direction: Direction;
  isArabic: boolean;
  isEnglish: boolean;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, fallback?: string) => string;
}

// Arabic translations for AQLHR platform
const translations = {
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.recruitment': 'التوظيف والإعداد',
    'nav.employees': 'الموظفون',
    'nav.payroll': 'كشوف المرتبات',
    'nav.performance': 'إدارة الأداء',
    'nav.training': 'التدريب والتطوير',
    'nav.compliance': 'الامتثال',
    'nav.analytics': 'التحليلات',
    'nav.settings': 'الإعدادات',
    
    // Recruitment Module
    'recruitment.title': 'التوظيف والإعداد',
    'recruitment.subtitle': 'إدارة شاملة لعمليات التوظيف والإعداد مع التكامل مع المراجع السعودية',
    'recruitment.dashboard': 'لوحة التحكم',
    'recruitment.localPlatforms': 'المنصات المحلية',
    'recruitment.internationalAgents': 'الوكلاء الدوليون',
    'recruitment.communicationHub': 'مركز الاتصالات',
    'recruitment.compliance': 'الامتثال',
    'recruitment.analytics': 'التحليلات',
    
    // Metrics
    'metrics.activeCandidates': 'المرشحون النشطون',
    'metrics.openPositions': 'الوظائف المفتوحة',
    'metrics.hiresThisMonth': 'عمليات التوظيف هذا الشهر',
    'metrics.averageTimeToHire': 'متوسط وقت التوظيف',
    'metrics.days': 'يوم',
    
    // Quick Actions
    'actions.title': 'الإجراءات السريعة',
    'actions.addPosition': 'إضافة وظيفة جديدة',
    'actions.addPositionDesc': 'إنشاء وظيفة جديدة مع التكامل مع قوى',
    'actions.reviewCVs': 'مراجعة السير الذاتية',
    'actions.reviewCVsDesc': 'مراجعة السير الذاتية المقدمة',
    'actions.onboardEmployee': 'إعداد موظف جديد',
    'actions.onboardEmployeeDesc': 'بدء عملية إعداد موظف جديد',
    'actions.createJobOffer': 'إنشاء عرض عمل',
    'actions.createJobOfferDesc': 'إنشاء عرض عمل شامل مع سير عمل الموافقة',
    'actions.recruitmentReports': 'تقارير التوظيف',
    'actions.recruitmentReportsDesc': 'عرض تقارير وتحليلات التوظيف',
    
    // Platform Status
    'platform.status.active': 'نشط',
    'platform.status.inactive': 'غير نشط',
    'platform.status.maintenance': 'صيانة',
    'platform.status.error': 'خطأ',
    
    // Saudi Platforms
    'platforms.qiwa': 'قوى',
    'platforms.gosi': 'التأمينات الاجتماعية',
    'platforms.mol': 'وزارة العمل',
    'platforms.hrsd': 'وزارة الموارد البشرية',
    'platforms.absher': 'أبشر',
    'platforms.bayt': 'بيت.كوم السعودية',
    'platforms.linkedin': 'لينكد إن السعودية',
    'platforms.gulftalent': 'جلف تالنت',
    'platforms.naukrigulf': 'نوكري جلف',
    'platforms.indeed': 'إنديد السعودية',
    'platforms.monster': 'مونستر السعودية',
    'platforms.tanqeeb': 'تنقيب',
    'platforms.akhtaboot': 'أختابوت',
    'platforms.mihnati': 'مهنتي',
    'platforms.jadara': 'جدارة',
    
    // International Clusters
    'international.gccCluster': 'مجموعة دول الخليج',
    'international.southAsianNetwork': 'الشبكة الآسيوية الجنوبية',
    'international.westernTalent': 'المواهب الغربية',
    'international.africanAlliance': 'التحالف الأفريقي',
    'international.agents': 'وكيل',
    'international.candidates': 'مرشح',
    
    // Compliance Services
    'compliance.gosi': 'التأمينات الاجتماعية',
    'compliance.qiwa': 'قوى',
    'compliance.mol': 'وزارة العمل',
    'compliance.hrsd': 'الموارد البشرية',
    'compliance.absher': 'أبشر',
    'compliance.wps': 'نظام حماية الأجور',
    'compliance.nitaqat': 'نطاقات',
    'compliance.overallScore': 'النتيجة الإجمالية',
    
    // Communication Hub
    'communication.title': 'مركز الاتصالات المركزي',
    'communication.subtitle': 'رسائل فورية مع مراقبة الامتثال',
    'communication.activeChats': 'المحادثات النشطة',
    'communication.responseRate': 'معدل الاستجابة',
    'communication.avgResponse': 'متوسط الاستجابة',
    'communication.recentConversations': 'المحادثات الأخيرة',
    'communication.complianceAlerts': 'تنبيهات الامتثال',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.view': 'عرض',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.refresh': 'تحديث',
    'common.close': 'إغلاق',
    'common.open': 'فتح',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.all': 'الكل',
    'common.none': 'لا شيء',
    'common.select': 'اختيار',
    'common.upload': 'رفع',
    'common.download': 'تحميل',
    'common.print': 'طباعة',
    'common.share': 'مشاركة',
    'common.copy': 'نسخ',
    'common.paste': 'لصق',
    'common.cut': 'قص',
    'common.undo': 'تراجع',
    'common.redo': 'إعادة',
    'common.help': 'مساعدة',
    'common.about': 'حول',
    'common.contact': 'اتصال',
    'common.support': 'دعم',
    'common.feedback': 'ملاحظات',
    'common.version': 'الإصدار',
    'common.update': 'تحديث',
    'common.upgrade': 'ترقية',
    'common.downgrade': 'تخفيض',
    'common.install': 'تثبيت',
    'common.uninstall': 'إلغاء التثبيت',
    'common.configure': 'تكوين',
    'common.setup': 'إعداد',
    'common.reset': 'إعادة تعيين',
    'common.restore': 'استعادة',
    'common.backup': 'نسخ احتياطي',
    'common.sync': 'مزامنة',
    'common.connect': 'اتصال',
    'common.disconnect': 'قطع الاتصال',
    'common.online': 'متصل',
    'common.offline': 'غير متصل',
    'common.available': 'متاح',
    'common.unavailable': 'غير متاح',
    'common.enabled': 'مفعل',
    'common.disabled': 'معطل',
    'common.active': 'نشط',
    'common.inactive': 'غير نشط',
    'common.pending': 'معلق',
    'common.approved': 'موافق عليه',
    'common.rejected': 'مرفوض',
    'common.completed': 'مكتمل',
    'common.inProgress': 'قيد التنفيذ',
    'common.failed': 'فشل',
    'common.cancelled': 'ملغي',
    'common.expired': 'منتهي الصلاحية',
    'common.valid': 'صالح',
    'common.invalid': 'غير صالح',
    'common.required': 'مطلوب',
    'common.optional': 'اختياري',
    'common.recommended': 'موصى به',
    'common.deprecated': 'مهجور',
    'common.new': 'جديد',
    'common.old': 'قديم',
    'common.latest': 'الأحدث',
    'common.previous': 'السابق',
    'common.next': 'التالي',
    'common.first': 'الأول',
    'common.last': 'الأخير',
    'common.total': 'المجموع',
    'common.count': 'العدد',
    'common.percentage': 'النسبة المئوية',
    'common.average': 'المتوسط',
    'common.minimum': 'الحد الأدنى',
    'common.maximum': 'الحد الأقصى',
    'common.range': 'النطاق',
    'common.limit': 'الحد',
    'common.quota': 'الحصة',
    'common.budget': 'الميزانية',
    'common.cost': 'التكلفة',
    'common.price': 'السعر',
    'common.value': 'القيمة',
    'common.amount': 'المبلغ',
    'common.quantity': 'الكمية',
    'common.size': 'الحجم',
    'common.weight': 'الوزن',
    'common.length': 'الطول',
    'common.width': 'العرض',
    'common.height': 'الارتفاع',
    'common.depth': 'العمق',
    'common.area': 'المساحة',
    'common.volume': 'الحجم',
    'common.capacity': 'السعة',
    'common.speed': 'السرعة',
    'common.duration': 'المدة',
    'common.frequency': 'التكرار',
    'common.interval': 'الفترة',
    'common.delay': 'التأخير',
    'common.timeout': 'انتهاء المهلة',
    'common.retry': 'إعادة المحاولة',
    'common.attempt': 'المحاولة',
    'common.trial': 'التجربة',
    'common.test': 'اختبار',
    'common.demo': 'عرض توضيحي',
    'common.sample': 'عينة',
    'common.example': 'مثال',
    'common.template': 'قالب',
    'common.pattern': 'نمط',
    'common.format': 'تنسيق',
    'common.style': 'نمط',
    'common.theme': 'موضوع',
    'common.color': 'لون',
    'common.background': 'خلفية',
    'common.foreground': 'مقدمة',
    'common.border': 'حدود',
    'common.margin': 'هامش',
    'common.padding': 'حشو',
    'common.spacing': 'تباعد',
    'common.alignment': 'محاذاة',
    'common.position': 'موضع',
    'common.location': 'موقع',
    'common.address': 'عنوان',
    'common.coordinates': 'إحداثيات',
    'common.latitude': 'خط العرض',
    'common.longitude': 'خط الطول',
    'common.altitude': 'الارتفاع',
    'common.elevation': 'الارتفاع',
    'common.distance': 'المسافة',
    'common.direction': 'الاتجاه',
    'common.orientation': 'التوجه',
    'common.rotation': 'الدوران',
    'common.scale': 'المقياس',
    'common.zoom': 'تكبير',
    'common.focus': 'تركيز',
    'common.blur': 'ضبابية',
    'common.opacity': 'الشفافية',
    'common.transparency': 'الشفافية',
    'common.visibility': 'الرؤية',
    'common.display': 'عرض',
    'common.show': 'إظهار',
    'common.hide': 'إخفاء',
    'common.toggle': 'تبديل',
    'common.switch': 'تبديل',
    'common.change': 'تغيير',
    'common.modify': 'تعديل',
    'common.update': 'تحديث',
    'common.upgrade': 'ترقية',
    'common.downgrade': 'تخفيض',
    'common.migrate': 'ترحيل',
    'common.transfer': 'نقل',
    'common.move': 'نقل',
    'common.copy': 'نسخ',
    'common.duplicate': 'تكرار',
    'common.clone': 'استنساخ',
    'common.merge': 'دمج',
    'common.split': 'تقسيم',
    'common.combine': 'دمج',
    'common.separate': 'فصل',
    'common.join': 'انضمام',
    'common.leave': 'مغادرة',
    'common.enter': 'دخول',
    'common.exit': 'خروج',
    'common.start': 'بداية',
    'common.stop': 'توقف',
    'common.pause': 'إيقاف مؤقت',
    'common.resume': 'استئناف',
    'common.continue': 'متابعة',
    'common.finish': 'إنهاء',
    'common.complete': 'إكمال',
    'common.submit': 'إرسال',
    'common.send': 'إرسال',
    'common.receive': 'استقبال',
    'common.get': 'الحصول على',
    'common.set': 'تعيين',
    'common.put': 'وضع',
    'common.post': 'نشر',
    'common.delete': 'حذف',
    'common.remove': 'إزالة',
    'common.clear': 'مسح',
    'common.clean': 'تنظيف',
    'common.purge': 'تطهير',
    'common.flush': 'تفريغ',
    'common.empty': 'فارغ',
    'common.full': 'ممتلئ',
    'common.partial': 'جزئي',
    'common.complete': 'كامل',
    'common.incomplete': 'غير مكتمل',
    'common.missing': 'مفقود',
    'common.found': 'موجود',
    'common.lost': 'مفقود',
    'common.recovered': 'مستعاد',
    'common.damaged': 'تالف',
    'common.broken': 'مكسور',
    'common.fixed': 'مثبت',
    'common.repaired': 'مُصلح',
    'common.replaced': 'مستبدل',
    'common.upgraded': 'مُحدث',
    'common.downgraded': 'مُخفض',
    'common.optimized': 'محسن',
    'common.improved': 'محسن',
    'common.enhanced': 'محسن',
    'common.advanced': 'متقدم',
    'common.basic': 'أساسي',
    'common.simple': 'بسيط',
    'common.complex': 'معقد',
    'common.easy': 'سهل',
    'common.difficult': 'صعب',
    'common.hard': 'صعب',
    'common.soft': 'ناعم',
    'common.smooth': 'ناعم',
    'common.rough': 'خشن',
    'common.sharp': 'حاد',
    'common.blunt': 'كليل',
    'common.bright': 'مشرق',
    'common.dark': 'مظلم',
    'common.light': 'فاتح',
    'common.heavy': 'ثقيل',
    'common.fast': 'سريع',
    'common.slow': 'بطيء',
    'common.quick': 'سريع',
    'common.instant': 'فوري',
    'common.immediate': 'فوري',
    'common.delayed': 'مؤجل',
    'common.scheduled': 'مجدول',
    'common.planned': 'مخطط',
    'common.unplanned': 'غير مخطط',
    'common.expected': 'متوقع',
    'common.unexpected': 'غير متوقع',
    'common.predicted': 'متنبأ به',
    'common.estimated': 'مقدر',
    'common.calculated': 'محسوب',
    'common.measured': 'مقاس',
    'common.recorded': 'مسجل',
    'common.logged': 'مسجل',
    'common.tracked': 'متتبع',
    'common.monitored': 'مراقب',
    'common.observed': 'ملاحظ',
    'common.watched': 'مراقب',
    'common.supervised': 'مُشرف عليه',
    'common.managed': 'مُدار',
    'common.controlled': 'مُتحكم فيه',
    'common.automated': 'آلي',
    'common.manual': 'يدوي',
    'common.automatic': 'تلقائي',
    'common.custom': 'مخصص',
    'common.default': 'افتراضي',
    'common.standard': 'قياسي',
    'common.premium': 'مميز',
    'common.professional': 'احترافي',
    'common.enterprise': 'مؤسسي',
    'common.personal': 'شخصي',
    'common.private': 'خاص',
    'common.public': 'عام',
    'common.shared': 'مشترك',
    'common.exclusive': 'حصري',
    'common.limited': 'محدود',
    'common.unlimited': 'غير محدود',
    'common.restricted': 'مقيد',
    'common.unrestricted': 'غير مقيد',
    'common.allowed': 'مسموح',
    'common.forbidden': 'محظور',
    'common.permitted': 'مسموح',
    'common.denied': 'مرفوض',
    'common.granted': 'ممنوح',
    'common.revoked': 'مُلغى',
    'common.suspended': 'معلق',
    'common.resumed': 'مستأنف',
    'common.terminated': 'منتهي',
    'common.extended': 'ممدد',
    'common.renewed': 'مُجدد',
    'common.expired': 'منتهي الصلاحية',
    'common.valid': 'صالح',
    'common.invalid': 'غير صالح',
    'common.verified': 'مُتحقق منه',
    'common.unverified': 'غير مُتحقق منه',
    'common.confirmed': 'مؤكد',
    'common.unconfirmed': 'غير مؤكد',
    'common.authenticated': 'مُصادق عليه',
    'common.unauthenticated': 'غير مُصادق عليه',
    'common.authorized': 'مُخول',
    'common.unauthorized': 'غير مُخول',
    'common.secure': 'آمن',
    'common.insecure': 'غير آمن',
    'common.encrypted': 'مُشفر',
    'common.decrypted': 'مُفكك التشفير',
    'common.protected': 'محمي',
    'common.unprotected': 'غير محمي',
    'common.safe': 'آمن',
    'common.unsafe': 'غير آمن',
    'common.stable': 'مستقر',
    'common.unstable': 'غير مستقر',
    'common.reliable': 'موثوق',
    'common.unreliable': 'غير موثوق',
    'common.consistent': 'متسق',
    'common.inconsistent': 'غير متسق',
    'common.accurate': 'دقيق',
    'common.inaccurate': 'غير دقيق',
    'common.precise': 'دقيق',
    'common.imprecise': 'غير دقيق',
    'common.exact': 'دقيق',
    'common.approximate': 'تقريبي',
    'common.rough': 'تقريبي',
    'common.detailed': 'مفصل',
    'common.summary': 'ملخص',
    'common.overview': 'نظرة عامة',
    'common.preview': 'معاينة',
    'common.review': 'مراجعة',
    'common.audit': 'تدقيق',
    'common.inspection': 'فحص',
    'common.examination': 'فحص',
    'common.analysis': 'تحليل',
    'common.evaluation': 'تقييم',
    'common.assessment': 'تقييم',
    'common.measurement': 'قياس',
    'common.comparison': 'مقارنة',
    'common.contrast': 'تباين',
    'common.difference': 'فرق',
    'common.similarity': 'تشابه',
    'common.match': 'تطابق',
    'common.mismatch': 'عدم تطابق',
    'common.correlation': 'ارتباط',
    'common.relationship': 'علاقة',
    'common.connection': 'اتصال',
    'common.link': 'رابط',
    'common.association': 'ارتباط',
    'common.dependency': 'تبعية',
    'common.independence': 'استقلالية',
    'common.isolation': 'عزل',
    'common.integration': 'تكامل',
    'common.separation': 'فصل',
    'common.division': 'قسم',
    'common.multiplication': 'ضرب',
    'common.addition': 'جمع',
    'common.subtraction': 'طرح',
    'common.calculation': 'حساب',
    'common.computation': 'حوسبة',
    'common.processing': 'معالجة',
    'common.execution': 'تنفيذ',
    'common.operation': 'عملية',
    'common.function': 'وظيفة',
    'common.method': 'طريقة',
    'common.procedure': 'إجراء',
    'common.process': 'عملية',
    'common.workflow': 'سير العمل',
    'common.pipeline': 'خط الأنابيب',
    'common.sequence': 'تسلسل',
    'common.order': 'ترتيب',
    'common.arrangement': 'ترتيب',
    'common.organization': 'تنظيم',
    'common.structure': 'هيكل',
    'common.architecture': 'هندسة معمارية',
    'common.design': 'تصميم',
    'common.layout': 'تخطيط',
    'common.format': 'تنسيق',
    'common.style': 'نمط',
    'common.appearance': 'مظهر',
    'common.look': 'مظهر',
    'common.feel': 'شعور',
    'common.experience': 'تجربة',
    'common.interface': 'واجهة',
    'common.interaction': 'تفاعل',
    'common.communication': 'تواصل',
    'common.conversation': 'محادثة',
    'common.dialogue': 'حوار',
    'common.discussion': 'نقاش',
    'common.debate': 'جدال',
    'common.argument': 'حجة',
    'common.reasoning': 'استدلال',
    'common.logic': 'منطق',
    'common.thinking': 'تفكير',
    'common.consideration': 'اعتبار',
    'common.reflection': 'تأمل',
    'common.contemplation': 'تأمل',
    'common.meditation': 'تأمل',
    'common.concentration': 'تركيز',
    'common.attention': 'انتباه',
    'common.awareness': 'وعي',
    'common.consciousness': 'وعي',
    'common.understanding': 'فهم',
    'common.comprehension': 'فهم',
    'common.knowledge': 'معرفة',
    'common.information': 'معلومات',
    'common.data': 'بيانات',
    'common.facts': 'حقائق',
    'common.details': 'تفاصيل',
    'common.specifics': 'تفاصيل محددة',
    'common.particulars': 'تفاصيل',
    'common.elements': 'عناصر',
    'common.components': 'مكونات',
    'common.parts': 'أجزاء',
    'common.pieces': 'قطع',
    'common.fragments': 'شظايا',
    'common.segments': 'شرائح',
    'common.sections': 'أقسام',
    'common.chapters': 'فصول',
    'common.pages': 'صفحات',
    'common.lines': 'خطوط',
    'common.words': 'كلمات',
    'common.characters': 'أحرف',
    'common.symbols': 'رموز',
    'common.signs': 'علامات',
    'common.marks': 'علامات',
    'common.indicators': 'مؤشرات',
    'common.signals': 'إشارات',
    'common.alerts': 'تنبيهات',
    'common.warnings': 'تحذيرات',
    'common.notifications': 'إشعارات',
    'common.messages': 'رسائل',
    'common.communications': 'اتصالات',
    'common.transmissions': 'إرسالات',
    'common.broadcasts': 'بث',
    'common.announcements': 'إعلانات',
    'common.declarations': 'إعلانات',
    'common.statements': 'بيانات',
    'common.reports': 'تقارير',
    'common.documents': 'وثائق',
    'common.files': 'ملفات',
    'common.records': 'سجلات',
    'common.logs': 'سجلات',
    'common.entries': 'إدخالات',
    'common.items': 'عناصر',
    'common.objects': 'كائنات',
    'common.entities': 'كيانات',
    'common.instances': 'حالات',
    'common.examples': 'أمثلة',
    'common.samples': 'عينات',
    'common.specimens': 'عينات',
    'common.models': 'نماذج',
    'common.prototypes': 'نماذج أولية',
    'common.templates': 'قوالب',
    'common.patterns': 'أنماط',
    'common.designs': 'تصاميم',
    'common.blueprints': 'مخططات',
    'common.plans': 'خطط',
    'common.strategies': 'استراتيجيات',
    'common.tactics': 'تكتيكات',
    'common.approaches': 'مناهج',
    'common.methods': 'طرق',
    'common.techniques': 'تقنيات',
    'common.procedures': 'إجراءات',
    'common.processes': 'عمليات',
    'common.operations': 'عمليات',
    'common.activities': 'أنشطة',
    'common.actions': 'إجراءات',
    'common.tasks': 'مهام',
    'common.jobs': 'وظائف',
    'common.assignments': 'مهام',
    'common.duties': 'واجبات',
    'common.responsibilities': 'مسؤوليات',
    'common.obligations': 'التزامات',
    'common.commitments': 'التزامات',
    'common.promises': 'وعود',
    'common.agreements': 'اتفاقيات',
    'common.contracts': 'عقود',
    'common.deals': 'صفقات',
    'common.transactions': 'معاملات',
    'common.exchanges': 'تبادلات',
    'common.trades': 'تجارة',
    'common.business': 'أعمال',
    'common.commerce': 'تجارة',
    'common.industry': 'صناعة',
    'common.sector': 'قطاع',
    'common.field': 'مجال',
    'common.area': 'منطقة',
    'common.domain': 'مجال',
    'common.territory': 'إقليم',
    'common.region': 'منطقة',
    'common.zone': 'منطقة',
    'common.district': 'منطقة',
    'common.neighborhood': 'حي',
    'common.community': 'مجتمع',
    'common.society': 'مجتمع',
    'common.group': 'مجموعة',
    'common.team': 'فريق',
    'common.crew': 'طاقم',
    'common.staff': 'موظفون',
    'common.personnel': 'أفراد',
    'common.workforce': 'قوة عاملة',
    'common.employees': 'موظفون',
    'common.workers': 'عمال',
    'common.laborers': 'عمال',
    'common.professionals': 'محترفون',
    'common.experts': 'خبراء',
    'common.specialists': 'متخصصون',
    'common.consultants': 'استشاريون',
    'common.advisors': 'مستشارون',
    'common.mentors': 'موجهون',
    'common.coaches': 'مدربون',
    'common.trainers': 'مدربون',
    'common.instructors': 'مدربون',
    'common.teachers': 'معلمون',
    'common.educators': 'مربون',
    'common.professors': 'أساتذة',
    'common.lecturers': 'محاضرون',
    'common.speakers': 'متحدثون',
    'common.presenters': 'مقدمون',
    'common.hosts': 'مضيفون',
    'common.moderators': 'مشرفون',
    'common.facilitators': 'ميسرون',
    'common.coordinators': 'منسقون',
    'common.organizers': 'منظمون',
    'common.planners': 'مخططون',
    'common.managers': 'مديرون',
    'common.supervisors': 'مشرفون',
    'common.administrators': 'إداريون',
    'common.executives': 'تنفيذيون',
    'common.directors': 'مديرون',
    'common.officers': 'ضباط',
    'common.officials': 'مسؤولون',
    'common.authorities': 'سلطات',
    'common.leaders': 'قادة',
    'common.chiefs': 'رؤساء',
    'common.heads': 'رؤساء',
    'common.bosses': 'رؤساء',
    'common.owners': 'مالكون',
    'common.proprietors': 'مالكون',
    'common.founders': 'مؤسسون',
    'common.creators': 'منشئون',
    'common.inventors': 'مخترعون',
    'common.innovators': 'مبتكرون',
    'common.pioneers': 'رواد',
    'common.explorers': 'مستكشفون',
    'common.researchers': 'باحثون',
    'common.scientists': 'علماء',
    'common.scholars': 'علماء',
    'common.academics': 'أكاديميون',
    'common.students': 'طلاب',
    'common.learners': 'متعلمون',
    'common.trainees': 'متدربون',
    'common.apprentices': 'متدربون',
    'common.interns': 'متدربون',
    'common.volunteers': 'متطوعون',
    'common.participants': 'مشاركون',
    'common.members': 'أعضاء',
    'common.users': 'مستخدمون',
    'common.customers': 'عملاء',
    'common.clients': 'عملاء',
    'common.patrons': 'رعاة',
    'common.supporters': 'داعمون',
    'common.sponsors': 'رعاة',
    'common.donors': 'متبرعون',
    'common.contributors': 'مساهمون',
    'common.partners': 'شركاء',
    'common.allies': 'حلفاء',
    'common.associates': 'شركاء',
    'common.colleagues': 'زملاء',
    'common.peers': 'أقران',
    'common.friends': 'أصدقاء',
    'common.companions': 'رفاق',
    'common.neighbors': 'جيران',
    'common.relatives': 'أقارب',
    'common.family': 'عائلة',
    'common.household': 'أسرة',
    'common.home': 'منزل',
    'common.house': 'بيت',
    'common.residence': 'مقر إقامة',
    'common.dwelling': 'مسكن',
    'common.accommodation': 'إقامة',
    'common.lodging': 'إقامة',
    'common.shelter': 'مأوى',
    'common.refuge': 'ملجأ',
    'common.sanctuary': 'ملاذ',
    'common.haven': 'ملاذ آمن',
    'common.retreat': 'ملاذ',
    'common.hideout': 'مخبأ',
    'common.hideaway': 'مخبأ',
    'common.escape': 'هروب',
    'common.exit': 'مخرج',
    'common.departure': 'مغادرة',
    'common.leaving': 'مغادرة',
    'common.going': 'ذهاب',
    'common.coming': 'قدوم',
    'common.arrival': 'وصول',
    'common.entrance': 'مدخل',
    'common.entry': 'دخول',
    'common.access': 'وصول',
    'common.admission': 'قبول',
    'common.acceptance': 'قبول',
    'common.approval': 'موافقة',
    'common.permission': 'إذن',
    'common.authorization': 'تخويل',
    'common.clearance': 'تصريح',
    'common.license': 'رخصة',
    'common.permit': 'تصريح',
    'common.certificate': 'شهادة',
    'common.diploma': 'دبلوم',
    'common.degree': 'درجة',
    'common.qualification': 'مؤهل',
    'common.credential': 'اعتماد',
    'common.certification': 'شهادة',
    'common.accreditation': 'اعتماد',
    'common.recognition': 'اعتراف',
    'common.acknowledgment': 'إقرار',
    'common.appreciation': 'تقدير',
    'common.gratitude': 'امتنان',
    'common.thanks': 'شكر',
    'common.praise': 'مدح',
    'common.compliment': 'مجاملة',
    'common.congratulations': 'تهانينا',
    'common.celebration': 'احتفال',
    'common.party': 'حفلة',
    'common.event': 'حدث',
    'common.occasion': 'مناسبة',
    'common.ceremony': 'حفل',
    'common.ritual': 'طقوس',
    'common.tradition': 'تقليد',
    'common.custom': 'عادة',
    'common.practice': 'ممارسة',
    'common.habit': 'عادة',
    'common.routine': 'روتين',
    'common.schedule': 'جدول',
    'common.timetable': 'جدول زمني',
    'common.agenda': 'جدول أعمال',
    'common.program': 'برنامج',
    'common.plan': 'خطة',
    'common.project': 'مشروع',
    'common.initiative': 'مبادرة',
    'common.campaign': 'حملة',
    'common.mission': 'مهمة',
    'common.quest': 'مهمة',
    'common.journey': 'رحلة',
    'common.trip': 'رحلة',
    'common.travel': 'سفر',
    'common.voyage': 'رحلة',
    'common.expedition': 'بعثة',
    'common.adventure': 'مغامرة',
    'common.exploration': 'استكشاف',
    'common.discovery': 'اكتشاف',
    'common.finding': 'اكتشاف',
    'common.result': 'نتيجة',
    'common.outcome': 'نتيجة',
    'common.consequence': 'نتيجة',
    'common.effect': 'تأثير',
    'common.impact': 'تأثير',
    'common.influence': 'تأثير',
    'common.power': 'قوة',
    'common.strength': 'قوة',
    'common.force': 'قوة',
    'common.energy': 'طاقة',
    'common.vitality': 'حيوية',
    'common.vigor': 'نشاط',
    'common.enthusiasm': 'حماس',
    'common.passion': 'شغف',
    'common.love': 'حب',
    'common.affection': 'عاطفة',
    'common.emotion': 'عاطفة',
    'common.feeling': 'شعور',
    'common.sentiment': 'شعور',
    'common.mood': 'مزاج',
    'common.atmosphere': 'جو',
    'common.environment': 'بيئة',
    'common.setting': 'إعداد',
    'common.context': 'سياق',
    'common.situation': 'وضع',
    'common.condition': 'حالة',
    'common.state': 'حالة',
    'common.status': 'حالة',
    'common.position': 'موضع',
    'common.place': 'مكان',
    'common.spot': 'مكان',
    'common.point': 'نقطة',
    'common.moment': 'لحظة',
    'common.instant': 'لحظة',
    'common.time': 'وقت',
    'common.period': 'فترة',
    'common.duration': 'مدة',
    'common.length': 'طول',
    'common.extent': 'مدى',
    'common.scope': 'نطاق',
    'common.range': 'نطاق',
    'common.span': 'امتداد',
    'common.reach': 'وصول',
    'common.coverage': 'تغطية',
    'common.inclusion': 'إدراج',
    'common.exclusion': 'استبعاد',
    'common.omission': 'إغفال',
    'common.absence': 'غياب',
    'common.presence': 'حضور',
    'common.existence': 'وجود',
    'common.being': 'كائن',
    'common.entity': 'كيان',
    'common.thing': 'شيء',
    'common.item': 'عنصر',
    'common.object': 'كائن',
    'common.subject': 'موضوع',
    'common.topic': 'موضوع',
    'common.theme': 'موضوع',
    'common.matter': 'مسألة',
    'common.issue': 'قضية',
    'common.problem': 'مشكلة',
    'common.challenge': 'تحدي',
    'common.difficulty': 'صعوبة',
    'common.obstacle': 'عقبة',
    'common.barrier': 'حاجز',
    'common.hurdle': 'عقبة',
    'common.impediment': 'عائق',
    'common.hindrance': 'عائق',
    'common.obstruction': 'عائق',
    'common.blockage': 'انسداد',
    'common.jam': 'ازدحام',
    'common.congestion': 'ازدحام',
    'common.traffic': 'حركة المرور',
    'common.flow': 'تدفق',
    'common.stream': 'تيار',
    'common.current': 'تيار',
    'common.trend': 'اتجاه',
    'common.direction': 'اتجاه',
    'common.course': 'مسار',
    'common.path': 'مسار',
    'common.route': 'طريق',
    'common.way': 'طريق',
    'common.road': 'طريق',
    'common.street': 'شارع',
    'common.avenue': 'شارع',
    'common.boulevard': 'شارع',
    'common.lane': 'ممر',
    'common.alley': 'زقاق',
    'common.passage': 'ممر',
    'common.corridor': 'ممر',
    'common.hallway': 'ممر',
    'common.hall': 'قاعة',
    'common.room': 'غرفة',
    'common.chamber': 'غرفة',
    'common.space': 'مساحة',
    'common.area': 'منطقة',
    'common.zone': 'منطقة',
    'common.sector': 'قطاع',
    'common.section': 'قسم',
    'common.part': 'جزء',
    'common.portion': 'جزء',
    'common.piece': 'قطعة',
    'common.fragment': 'شظية',
    'common.segment': 'شريحة',
    'common.division': 'قسم',
    'common.category': 'فئة',
    'common.class': 'فئة',
    'common.type': 'نوع',
    'common.kind': 'نوع',
    'common.sort': 'نوع',
    'common.variety': 'تنوع',
    'common.diversity': 'تنوع',
    'common.difference': 'فرق',
    'common.distinction': 'تمييز',
    'common.contrast': 'تباين',
    'common.comparison': 'مقارنة',
    'common.similarity': 'تشابه',
    'common.resemblance': 'تشابه',
    'common.likeness': 'تشابه',
    'common.analogy': 'تشبيه',
    'common.metaphor': 'استعارة',
    'common.symbol': 'رمز',
    'common.sign': 'علامة',
    'common.mark': 'علامة',
    'common.indicator': 'مؤشر',
    'common.signal': 'إشارة',
    'common.clue': 'دليل',
    'common.hint': 'تلميح',
    'common.suggestion': 'اقتراح',
    'common.recommendation': 'توصية',
    'common.advice': 'نصيحة',
    'common.guidance': 'إرشاد',
    'common.direction': 'توجيه',
    'common.instruction': 'تعليمات',
    'common.command': 'أمر',
    'common.order': 'أمر',
    'common.request': 'طلب',
    'common.demand': 'طلب',
    'common.requirement': 'متطلب',
    'common.need': 'حاجة',
    'common.necessity': 'ضرورة',
    'common.essential': 'أساسي',
    'common.fundamental': 'أساسي',
    'common.basic': 'أساسي',
    'common.primary': 'أساسي',
    'common.main': 'رئيسي',
    'common.principal': 'رئيسي',
    'common.chief': 'رئيسي',
    'common.major': 'رئيسي',
    'common.important': 'مهم',
    'common.significant': 'مهم',
    'common.crucial': 'حاسم',
    'common.critical': 'حرج',
    'common.vital': 'حيوي',
    'common.essential': 'أساسي',
    'common.necessary': 'ضروري',
    'common.required': 'مطلوب',
    'common.mandatory': 'إلزامي',
    'common.compulsory': 'إجباري',
    'common.obligatory': 'إلزامي',
    'common.optional': 'اختياري',
    'common.voluntary': 'طوعي',
    'common.free': 'حر',
    'common.independent': 'مستقل',
    'common.autonomous': 'مستقل',
    'common.self-governing': 'حكم ذاتي',
    'common.sovereign': 'ذو سيادة',
    'common.supreme': 'أعلى',
    'common.ultimate': 'نهائي',
    'common.final': 'نهائي',
    'common.last': 'أخير',
    'common.latest': 'أحدث',
    'common.newest': 'أحدث',
    'common.recent': 'حديث',
    'common.current': 'حالي',
    'common.present': 'حاضر',
    'common.existing': 'موجود',
    'common.available': 'متاح',
    'common.accessible': 'قابل للوصول',
    'common.reachable': 'قابل للوصول',
    'common.attainable': 'قابل للتحقيق',
    'common.achievable': 'قابل للتحقيق',
    'common.possible': 'ممكن',
    'common.feasible': 'ممكن',
    'common.viable': 'قابل للحياة',
    'common.practical': 'عملي',
    'common.realistic': 'واقعي',
    'common.reasonable': 'معقول',
    'common.logical': 'منطقي',
    'common.rational': 'عقلاني',
    'common.sensible': 'معقول',
    'common.wise': 'حكيم',
    'common.smart': 'ذكي',
    'common.intelligent': 'ذكي',
    'common.clever': 'ذكي',
    'common.brilliant': 'لامع',
    'common.genius': 'عبقري',
    'common.talented': 'موهوب',
    'common.gifted': 'موهوب',
    'common.skilled': 'ماهر',
    'common.expert': 'خبير',
    'common.professional': 'محترف',
    'common.experienced': 'ذو خبرة',
    'common.qualified': 'مؤهل',
    'common.competent': 'كفء',
    'common.capable': 'قادر',
    'common.able': 'قادر',
    'common.powerful': 'قوي',
    'common.strong': 'قوي',
    'common.robust': 'قوي',
    'common.sturdy': 'متين',
    'common.solid': 'صلب',
    'common.firm': 'ثابت',
    'common.stable': 'مستقر',
    'common.steady': 'ثابت',
    'common.consistent': 'متسق',
    'common.reliable': 'موثوق',
    'common.dependable': 'يمكن الاعتماد عليه',
    'common.trustworthy': 'جدير بالثقة',
    'common.honest': 'صادق',
    'common.truthful': 'صادق',
    'common.genuine': 'حقيقي',
    'common.authentic': 'أصيل',
    'common.real': 'حقيقي',
    'common.actual': 'فعلي',
    'common.true': 'صحيح',
    'common.correct': 'صحيح',
    'common.right': 'صحيح',
    'common.proper': 'مناسب',
    'common.appropriate': 'مناسب',
    'common.suitable': 'مناسب',
    'common.fitting': 'مناسب',
    'common.relevant': 'ذو صلة',
    'common.pertinent': 'ذو صلة',
    'common.applicable': 'قابل للتطبيق',
    'common.useful': 'مفيد',
    'common.helpful': 'مفيد',
    'common.beneficial': 'مفيد',
    'common.advantageous': 'مفيد',
    'common.profitable': 'مربح',
    'common.valuable': 'قيم',
    'common.precious': 'ثمين',
    'common.important': 'مهم',
    'common.significant': 'مهم',
    'common.meaningful': 'ذو معنى',
    'common.purposeful': 'هادف',
    'common.intentional': 'مقصود',
    'common.deliberate': 'متعمد',
    'common.planned': 'مخطط',
    'common.organized': 'منظم',
    'common.structured': 'منظم',
    'common.systematic': 'منهجي',
    'common.methodical': 'منهجي',
    'common.orderly': 'منظم',
    'common.neat': 'مرتب',
    'common.tidy': 'مرتب',
    'common.clean': 'نظيف',
    'common.clear': 'واضح',
    'common.transparent': 'شفاف',
    'common.obvious': 'واضح',
    'common.evident': 'واضح',
    'common.apparent': 'واضح',
    'common.visible': 'مرئي',
    'common.noticeable': 'ملحوظ',
    'common.observable': 'قابل للملاحظة',
    'common.detectable': 'قابل للكشف',
    'common.recognizable': 'قابل للتعرف',
    'common.identifiable': 'قابل للتحديد',
    'common.distinguishable': 'قابل للتمييز',
    'common.unique': 'فريد',
    'common.special': 'خاص',
    'common.exceptional': 'استثنائي',
    'common.extraordinary': 'استثنائي',
    'common.remarkable': 'ملحوظ',
    'common.outstanding': 'متميز',
    'common.excellent': 'ممتاز',
    'common.superior': 'متفوق',
    'common.premium': 'مميز',
    'common.high-quality': 'عالي الجودة',
    'common.top-notch': 'من الدرجة الأولى',
    'common.first-class': 'من الدرجة الأولى',
    'common.world-class': 'عالمي المستوى',
    'common.international': 'دولي',
    'common.global': 'عالمي',
    'common.universal': 'عالمي',
    'common.comprehensive': 'شامل',
    'common.complete': 'كامل',
    'common.full': 'كامل',
    'common.entire': 'كامل',
    'common.whole': 'كامل',
    'common.total': 'إجمالي',
    'common.overall': 'إجمالي',
    'common.general': 'عام',
    'common.broad': 'واسع',
    'common.wide': 'واسع',
    'common.extensive': 'واسع',
    'common.vast': 'واسع',
    'common.huge': 'ضخم',
    'common.enormous': 'ضخم',
    'common.massive': 'ضخم',
    'common.giant': 'عملاق',
    'common.large': 'كبير',
    'common.big': 'كبير',
    'common.small': 'صغير',
    'common.tiny': 'صغير',
    'common.mini': 'صغير',
    'common.micro': 'صغير جداً',
    'common.nano': 'نانو',
    'common.ultra': 'فائق',
    'common.super': 'فائق',
    'common.mega': 'ضخم',
    'common.giga': 'جيجا',
    'common.tera': 'تيرا',
    'common.peta': 'بيتا',
    'common.exa': 'إكسا',
    'common.zetta': 'زيتا',
    'common.yotta': 'يوتا'
  },
  en: {
    // English translations (fallback)
    'nav.dashboard': 'Dashboard',
    'nav.recruitment': 'Recruitment & Onboarding',
    'nav.employees': 'Employees',
    'nav.payroll': 'Payroll',
    'nav.performance': 'Performance Management',
    'nav.training': 'Training & Development',
    'nav.compliance': 'Compliance',
    'nav.analytics': 'Analytics',
    'nav.settings': 'Settings',
    
    'recruitment.title': 'Recruitment & Onboarding',
    'recruitment.subtitle': 'Comprehensive recruitment and onboarding management with Saudi reference integration',
    'recruitment.dashboard': 'Dashboard',
    'recruitment.localPlatforms': 'Local Platforms',
    'recruitment.internationalAgents': 'International Agents',
    'recruitment.communicationHub': 'Communication Hub',
    'recruitment.compliance': 'Compliance',
    'recruitment.analytics': 'Analytics',
    
    'metrics.activeCandidates': 'Active Candidates',
    'metrics.openPositions': 'Open Positions',
    'metrics.hiresThisMonth': 'Hires This Month',
    'metrics.averageTimeToHire': 'Average Time to Hire',
    'metrics.days': 'days',
    
    'actions.title': 'Quick Actions',
    'actions.addPosition': 'Add New Position',
    'actions.addPositionDesc': 'Create new position with Qiwa integration',
    'actions.reviewCVs': 'Review CVs',
    'actions.reviewCVsDesc': 'Review submitted CVs',
    'actions.onboardEmployee': 'Onboard Employee',
    'actions.onboardEmployeeDesc': 'Start new employee onboarding',
    'actions.createJobOffer': 'Create Job Offer',
    'actions.createJobOfferDesc': 'Create comprehensive job offer with approval workflow',
    'actions.recruitmentReports': 'Recruitment Reports',
    'actions.recruitmentReportsDesc': 'View recruitment reports and analytics',
    
    'platform.status.active': 'Active',
    'platform.status.inactive': 'Inactive',
    'platform.status.maintenance': 'Maintenance',
    'platform.status.error': 'Error',
    
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.refresh': 'Refresh',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.all': 'All',
    'common.none': 'None',
    'common.select': 'Select',
    'common.upload': 'Upload',
    'common.download': 'Download'
  }
};

// Create context
const RTLLanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Provider component
export const RTLLanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // Check localStorage first, then default to Arabic
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('aqlhr-language');
      return (saved as Language) || 'ar';
    }
    return 'ar';
  });

  const direction: Direction = language === 'ar' ? 'rtl' : 'ltr';
  const isArabic = language === 'ar';
  const isEnglish = language === 'en';

  // Translation function
  const t = (key: string, fallback?: string): string => {
    const translation = translations[language]?.[key] || translations.en[key] || fallback || key;
    return translation;
  };

  // Set language with persistence and DOM updates
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    
    if (typeof window !== 'undefined') {
      // Save to localStorage
      localStorage.setItem('aqlhr-language', lang);
      
      // Update document attributes for RTL support
      const html = document.documentElement;
      const body = document.body;
      
      if (lang === 'ar') {
        html.setAttribute('dir', 'rtl');
        html.setAttribute('lang', 'ar');
        body.setAttribute('dir', 'rtl');
        body.classList.add('rtl');
        body.classList.remove('ltr');
      } else {
        html.setAttribute('dir', 'ltr');
        html.setAttribute('lang', 'en');
        body.setAttribute('dir', 'ltr');
        body.classList.add('ltr');
        body.classList.remove('rtl');
      }
      
      // Force re-render of the entire app
      window.dispatchEvent(new Event('languagechange'));
    }
  };

  // Toggle language
  const toggleLanguage = () => {
    setLanguage(language === 'ar' ? 'en' : 'ar');
  };

  // Initialize DOM on mount
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const html = document.documentElement;
      const body = document.body;
      
      if (language === 'ar') {
        html.setAttribute('dir', 'rtl');
        html.setAttribute('lang', 'ar');
        body.setAttribute('dir', 'rtl');
        body.classList.add('rtl');
        body.classList.remove('ltr');
      } else {
        html.setAttribute('dir', 'ltr');
        html.setAttribute('lang', 'en');
        body.setAttribute('dir', 'ltr');
        body.classList.add('ltr');
        body.classList.remove('rtl');
      }
    }
  }, [language]);

  const value: LanguageContextType = {
    language,
    direction,
    isArabic,
    isEnglish,
    setLanguage,
    toggleLanguage,
    t
  };

  return (
    <RTLLanguageContext.Provider value={value}>
      {children}
    </RTLLanguageContext.Provider>
  );
};

// Hook to use the context
export const useRTLLanguage = (): LanguageContextType => {
  const context = useContext(RTLLanguageContext);
  if (context === undefined) {
    throw new Error('useRTLLanguage must be used within a RTLLanguageProvider');
  }
  return context;
};

// HOC for RTL support
export const withRTL = <P extends object>(Component: React.ComponentType<P>) => {
  return React.forwardRef<any, P>((props, ref) => {
    const { direction, isArabic } = useRTLLanguage();
    
    return (
      <div dir={direction} className={isArabic ? 'rtl force-rtl' : 'ltr force-ltr'}>
        <Component {...props} ref={ref} />
      </div>
    );
  });
};

export default RTLLanguageContext;

