import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  let prompt = 'HR Document';
  let documentType = 'policy';
  let language = 'en';
  let companyName = 'AqlHR Company';

  try {
    const requestBody = await req.json();
    prompt = requestBody.prompt || 'HR Document';
    documentType = requestBody.documentType || 'policy';
    language = requestBody.language || 'en';
    companyName = requestBody.companyName || 'AqlHR Company';

    const openAIApiKey = Deno.env.get('OPENAI_API_KEY');
    if (!openAIApiKey) {
      throw new Error('OpenAI API key not configured');
    }

    const systemPrompts = {
      policy: language === 'ar' 
        ? `أنت خبير في كتابة السياسات المؤسسية للموارد البشرية. اكتب سياسة مهنية ومنظمة وفقاً للقوانين السعودية`
        : `You are an expert HR policy writer. Create a professional, well-structured policy document compliant with Saudi labor laws`,
      report: language === 'ar'
        ? `أنت خبير في إعداد التقارير التنفيذية للموارد البشرية. اكتب تقرير شامل ومفصل`
        : `You are an expert HR report analyst. Create a comprehensive, detailed executive report`,
      procedure: language === 'ar'
        ? `أنت خبير في كتابة الإجراءات التشغيلية للموارد البشرية. اكتب إجراء واضح ومفصل`
        : `You are an expert in HR operational procedures. Create clear, detailed step-by-step procedures`
    };

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openAIApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-3.5-turbo',
        messages: [
          {
            role: 'system',
            content: `${systemPrompts[documentType as keyof typeof systemPrompts]}. Format the output as a professional document with proper headings, sections, and structure. Include company name: ${companyName}`
          },
          {
            role: 'user',
            content: prompt
          }
        ],
        temperature: 0.7,
        max_tokens: 3000
      }),
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(`OpenAI API error: ${errorData.error?.message || 'Unknown error'}`);
    }

    const data = await response.json();
    const documentContent = data.choices[0].message.content;

    // Format as downloadable document
    const formattedDocument = `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>${companyName} - ${documentType} Document</title>
    <style>
        body { 
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
            line-height: 1.6; 
            margin: 40px; 
            color: #333;
            direction: ${language === 'ar' ? 'rtl' : 'ltr'};
        }
        h1, h2, h3 { color: #2c5282; margin-top: 30px; }
        h1 { border-bottom: 2px solid #2c5282; padding-bottom: 10px; }
        .header { text-align: center; margin-bottom: 40px; }
        .footer { margin-top: 40px; font-size: 12px; color: #666; text-align: center; }
        .section { margin: 20px 0; }
        ol, ul { margin: 15px 0; }
        li { margin: 5px 0; }
    </style>
</head>
<body>
    <div class="header">
        <h1>${companyName}</h1>
        <h2>${documentType.charAt(0).toUpperCase() + documentType.slice(1)} Document</h2>
        <p>Generated on: ${new Date().toLocaleDateString(language === 'ar' ? 'ar-SA' : 'en-US')}</p>
    </div>
    
    <div class="content">
        ${documentContent.replace(/\n/g, '<br>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}
    </div>
    
    <div class="footer">
        <p>Generated by AqlHR AI Document Assistant</p>
        <p>© ${new Date().getFullYear()} ${companyName}</p>
    </div>
</body>
</html>`;

    return new Response(JSON.stringify({
      success: true,
      document: {
        content: documentContent,
        html: formattedDocument,
        type: documentType,
        language: language,
        timestamp: new Date().toISOString()
      }
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (error) {
    console.error('Document generation error:', error);
    
    // Fallback document content
    const fallbackContent = language === 'ar' 
      ? `# ${documentType} وثيقة

## مقدمة
هذه الوثيقة تم إنشاؤها تلقائياً بناءً على طلبكم: ${prompt}

## الغرض
تهدف هذه الوثيقة إلى توضيح السياسات والإجراءات المتعلقة بالموضوع المطلوب.

## النطاق
تنطبق هذه الوثيقة على جميع الموظفين في ${companyName}.

## التفاصيل
يرجى مراجعة هذه الوثيقة مع فريق الموارد البشرية لضمان توافقها مع احتياجات المؤسسة.

## المراجعة
يجب مراجعة هذه الوثيقة بشكل دوري لضمان حداثتها وملاءمتها.`
      : `# ${documentType.charAt(0).toUpperCase() + documentType.slice(1)} Document

## Introduction
This document has been automatically generated based on your request: ${prompt}

## Purpose
This document aims to clarify policies and procedures related to the requested topic.

## Scope
This document applies to all employees at ${companyName}.

## Details
Please review this document with your HR team to ensure it meets your organization's needs.

## Review
This document should be reviewed periodically to ensure it remains current and relevant.`;

    const formattedDocument = `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>${companyName} - ${documentType} Document</title>
    <style>
        body { 
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
            line-height: 1.6; 
            margin: 40px; 
            color: #333;
            direction: ${language === 'ar' ? 'rtl' : 'ltr'};
        }
        h1, h2, h3 { color: #2c5282; margin-top: 30px; }
        h1 { border-bottom: 2px solid #2c5282; padding-bottom: 10px; }
        .header { text-align: center; margin-bottom: 40px; }
        .footer { margin-top: 40px; font-size: 12px; color: #666; text-align: center; }
        .section { margin: 20px 0; }
        ol, ul { margin: 15px 0; }
        li { margin: 5px 0; }
        .fallback-notice { background: #f0f4f8; padding: 15px; border-left: 4px solid #2c5282; margin: 20px 0; }
    </style>
</head>
<body>
    <div class="header">
        <h1>${companyName}</h1>
        <h2>${documentType.charAt(0).toUpperCase() + documentType.slice(1)} Document</h2>
        <p>Generated on: ${new Date().toLocaleDateString(language === 'ar' ? 'ar-SA' : 'en-US')}</p>
    </div>
    
    <div class="fallback-notice">
        <strong>${language === 'ar' ? 'ملاحظة:' : 'Note:'}</strong> 
        ${language === 'ar' 
          ? 'تم إنشاء هذه الوثيقة باستخدام نموذج افتراضي بسبب محدودية API. يرجى مراجعتها وتخصيصها حسب احتياجاتكم.'
          : 'This document was generated using a fallback template due to API limitations. Please review and customize as needed.'}
    </div>
    
    <div class="content">
        ${fallbackContent.replace(/\n/g, '<br>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/^# (.*)/gm, '<h1>$1</h1>').replace(/^## (.*)/gm, '<h2>$1</h2>')}
    </div>
    
    <div class="footer">
        <p>Generated by AqlHR AI Document Assistant</p>
        <p>© ${new Date().getFullYear()} ${companyName}</p>
    </div>
</body>
</html>`;

    return new Response(JSON.stringify({
      success: true,
      document: {
        content: fallbackContent,
        html: formattedDocument,
        type: documentType,
        language: language,
        timestamp: new Date().toISOString(),
        fallback: true
      },
      note: "Generated using fallback template due to API limitations"
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});