version: '3.8'

services:
  # API Gateway - Entry point for all requests
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - AUTH_SERVICE_URL=http://auth-service:3001
      - EMPLOYEE_SERVICE_URL=http://employee-service:3002
      - AI_SERVICE_URL=http://ai-service:3003
      - GOVERNMENT_SERVICE_URL=http://government-service:3004
      - ANALYTICS_SERVICE_URL=http://analytics-service:3005
    depends_on:
      - auth-service
      - employee-service
      - ai-service
      - government-service
      - analytics-service
    networks:
      - aqlhr-network

  # Authentication & Authorization Service
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=aqlhr_jwt_secret_key_2024
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://aqlhr_user:aqlhr_pass@postgres:5432/aqlhr_auth
    depends_on:
      - redis
      - postgres
    networks:
      - aqlhr-network

  # Employee Management Service
  employee-service:
    build: ./employee-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://aqlhr_user:aqlhr_pass@postgres:5432/aqlhr_employees
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - aqlhr-network

  # AI Orchestration Service
  ai-service:
    build: ./ai-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://aqlhr_user:aqlhr_pass@postgres:5432/aqlhr_ai
    depends_on:
      - redis
      - postgres
    networks:
      - aqlhr-network

  # Government Integration Service
  government-service:
    build: ./government-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - GOSI_API_URL=https://api.gosi.gov.sa
      - QIWA_API_URL=https://api.qiwa.sa
      - HRSD_API_URL=https://api.hrsd.gov.sa
      - DATABASE_URL=postgresql://aqlhr_user:aqlhr_pass@postgres:5432/aqlhr_government
    depends_on:
      - postgres
    networks:
      - aqlhr-network

  # Analytics & Reporting Service
  analytics-service:
    build: ./analytics-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://aqlhr_user:aqlhr_pass@postgres:5432/aqlhr_analytics
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - postgres
      - redis
      - elasticsearch
    networks:
      - aqlhr-network

  # Notification Service
  notification-service:
    build: ./notification-service
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
    depends_on:
      - redis
    networks:
      - aqlhr-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=aqlhr_main
      - POSTGRES_USER=aqlhr_user
      - POSTGRES_PASSWORD=aqlhr_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - aqlhr-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aqlhr-network

  # Elasticsearch for Analytics
  elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - aqlhr-network

  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api-gateway
    networks:
      - aqlhr-network

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:

networks:
  aqlhr-network:
    driver: bridge
